# Generated by Django 4.0.3 on 2023-02-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image', upload_to='media/'),
            preserve_default=False,
        ),
    ]
