# Generated by Django 4.0.3 on 2023-02-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='User',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
